<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Description>Blazor component for displaying toggle switch and checked interaction. This component allows you to easily place toggle switches throughout your user interface. It has a default layout and color scheme that can be customized for your application.</Description>
    <PackageTags>Blazor .NET Components WebAssembly Toggle ToggleSwitch</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.BlazorComponent.Core\D20Tek.BlazorComponent.Core.csproj" />
  </ItemGroup>

</Project>
