<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Description>A Blazor component for displaying transient toast notifications. This content-agnostic toast system provides a host, service, and positioning options that can be customized for your application.</Description>
    <PackageTags>Blazor .NET Components WebAssembly Toast Notification</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.BlazorComponent.Core\D20Tek.BlazorComponent.Core.csproj" />
  </ItemGroup>

</Project>
