<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Description>A Blazor component for rendering Markdown text as HTML. This component uses the Markdig library to convert Markdown to HTML and render it safely in your Blazor application.</Description>
    <PackageTags>Blazor; .NET Components; WebAssembly; Markdown; Markdig</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Markdig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.BlazorComponent.Core\D20Tek.BlazorComponent.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>D20Tek.BlazorComponents.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
