<Project>

  <PropertyGroup>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<LangVersion>latest</LangVersion>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <!-- Common package/repository metadata used by all packable projects -->
  <PropertyGroup>
	<Authors>DarthPedro</Authors>
	<Company>d20Tek</Company>
	<Copyright>Copyright (c) d20Tek. All rights reserved.</Copyright>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/d20Tek/blazor-components</PackageProjectUrl>
	<RepositoryUrl>https://github.com/d20Tek/blazor-components</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageReleaseNotes>Please read the latest release notes at: https://github.com/d20Tek/blazor-components/blob/main/ReleaseNotes.md</PackageReleaseNotes>
  </PropertyGroup>

</Project>
