<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>The core shared library for all d20Tek Blazor components. Contains shared component defintions, enumerations, and base types.</Description>
    <PackageTags>Blazor .NET Components WebAssembly</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
  </ItemGroup>

</Project>
